# Generated by Django 5.0.3 on 2024-03-04 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='identification_documents',
        ),
        migrations.RemoveField(
            model_name='identificationdocument',
            name='document',
        ),
        migrations.AddField(
            model_name='customuser',
            name='identification_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.identificationdocument'),
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_document_images')),
                ('identification_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.identificationdocument')),
            ],
        ),
    ]
