# Generated by Django 4.2.7 on 2024-03-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_identification_documents_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': '   Company'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': '     Users'},
        ),
        migrations.AlterModelOptions(
            name='documentimage',
            options={'verbose_name': 'Doc Image', 'verbose_name_plural': ' Doc Images'},
        ),
        migrations.AlterModelOptions(
            name='identificationdocument',
            options={'verbose_name': 'IDENTY Docs', 'verbose_name_plural': '  IDENTY Docs'},
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name': 'Individual', 'verbose_name_plural': '    Individuals'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
