# Generated by Django 5.0.3 on 2024-03-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
