# Generated by Django 5.0.3 on 2024-03-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_profession_delete_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
