# Generated by Django 5.0.3 on 2024-03-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_comission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='comission',
        ),
    ]
