# Generated by Django 5.0.3 on 2024-03-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_customuser_comission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Exclusive Agent', 'Exclusive Agent')], default='Agent', max_length=20),
        ),
    ]
