# Generated by Django 5.0.3 on 2024-03-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reffer_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
