# Generated by Django 5.0.3 on 2024-03-15 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_applicant_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='isPaymentClaim',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('account_holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=100)),
                ('payee_address', models.TextField()),
                ('bank_address', models.TextField()),
                ('swift_code', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Claimed', 'Claimed'), ('Approved', 'Approved'), ('Reject', 'Reject'), ('Paid', 'Paid')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
