# Generated by Django 5.0.3 on 2024-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_applicant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='bank_type',
            field=models.CharField(choices=[('Local', 'Local'), ('Foreign', 'Foreign')], default='Local', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='bank_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payee_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
