# Generated by Django 5.0.3 on 2024-03-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paymentrequest_bank_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('Claimed', 'Claimed'), ('Approved', 'Approved'), ('Reject', 'Reject'), ('Paid', 'Paid')], default='Claimed', max_length=10),
        ),
    ]
