# Generated by Django 5.0.3 on 2024-03-18 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='program',
            field=models.CharField(choices=[('FOUNDATION', 'Foundation'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD'), ('RESEARCH_BASED', 'Research Based')], max_length=20),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('FOUNDATION', 'Foundation'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD'), ('RESEARCH_BASED', 'Research Based')], max_length=50)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.university')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
    ]
