# Generated by Django 5.0.3 on 2024-03-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_applicant_program_program_subject_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
