# Generated by Django 5.0.3 on 2024-03-18 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_fee_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Applicant', 'verbose_name_plural': '      Applicant'},
        ),
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'verbose_name': 'ApplicationStatus', 'verbose_name_plural': '      ApplicationStatus'},
        ),
        migrations.AlterModelOptions(
            name='commissiontier',
            options={'verbose_name': 'CommissionTier', 'verbose_name_plural': '       CommissionTier'},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name': 'Fee', 'verbose_name_plural': ' Fee'},
        ),
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'verbose_name': 'PaymentRequest', 'verbose_name_plural': '    PaymentRequest'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Program', 'verbose_name_plural': '  Program'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': '  Subject'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': '      University'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='program',
        ),
        migrations.AddField(
            model_name='subject',
            name='program_type',
            field=models.CharField(choices=[('FOUNDATION', 'Foundation'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'PhD'), ('RESEARCH_BASED', 'Research Based')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.university'),
            preserve_default=False,
        ),
    ]
