# Generated by Django 5.0.3 on 2024-03-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'verbose_name': 'PaymentRequest', 'verbose_name_plural': '   PaymentRequest'},
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
