# Generated by Django 5.0.3 on 2024-03-18 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_paymentrequest_options_delete_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject'),
        ),
    ]
