# Generated by Django 4.2.7 on 2024-03-19 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_applicant_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='subject_pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
