# Generated by Django 4.2.7 on 2024-03-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subject_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='program',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='university',
        ),
    ]
