# Generated by Django 5.0.3 on 2024-03-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_applicant_program_remove_applicant_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='intake',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
